### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by eduinus** [nekosune/modularforcefieldsystem#10]
Hey hello! I suspect this is a build.gradle issue - I've been working on a fork of mffs for my own personal use - did a few minor edits

Unfortunately when I run gradlew build, it throws a series of errors about necessary packages not being found. I've added the ic2 api to the list of dependencies and its corresponding repository, but I'm also missing libs from "nekokittygames" e.g.

`C:\Users\(myusername)\Documents\Eclipse Projects\modularforcefieldsystem-1.10\build\sources\main\java\com\nekokittygames\mffs\common\item\ItemCardDataLink.java:4: error: package com.nekokittygames.mffs.libs does not exist
import com.nekokittygames.mffs.libs.LibMisc;`

I'm also missing the support in build.gradle for the buildcraft api, but I suspect I can fix that on my own.

**Comment by GaeaKat** [comment]
Ic2 and buildcraft were added to libs/ folder manually, not through gradle. The missing file, will fix when I update next
