### ISSUE TITLE
MFFS Permissions not working on server.

### ISSUE THREAD

**Issue by stavie131** [nekosune/modularforcefieldsystem#14]
The ability to teleport in and out of force fields on servers is not working. Tried to replicate the bug in singleplayer with no success since it actually worked. 

Here is the crash log:

https://pastebin.com/7jgFQFxB

**Comment by GaeaKat** [comment]
This will be fixed . Sorry

**Comment by stavie131** [comment]
kudos to for getting back to me so quickly! A fix for this would be amazing, I love what your doing for MFFS. Take the time you need. Just in case you're wondering the modpack im using is FTB Infinity
