### ISSUE TITLE
1.12

### ISSUE THREAD

**Issue by ghost** [nekosune/modularforcefieldsystem#22]
Hello!
Please update Modular Force Field System to 1.12 version.

Thanks!
PS. I would like to translate your plugin to Polish language, should I do it - is this project "alive"?

**Comment by Chocohead** [comment]
You'll probably want to watch #21 as that is the remaining bulk of a 1.12 port. If you want to translate it to Polish in the mean time you're welcome to.

**Comment by GaeaKat** [comment]
This is being sorted!
