### ISSUE TITLE
incoherence with monazit ore with Waterpower

### ISSUE THREAD

**Issue by 0Navis0** [nekosune/modularforcefieldsystem#3]
WaterPower and MFFS both adds mozanit ore, but the two ore aren't registered in the same way and don't drop the same ores. WaterPower is melted into neodymium while MFFS one is melted into forcicium. The suggestion I could give to this kind of situation is to rename the ore to something else like forcicium.

**Comment by GaeaKat** [comment]
Monazite is used as it is an actual mineral - https://en.wikipedia.org/wiki/Monazite

**Comment by 0Navis0** [comment]
Hm I suppose it's WaterPower that make the things work, anyway I close this issue for the time.

**Comment by GaeaKat** [comment]
I will make monazit / forcium oredictable in one of my next updates, as I state, this was mostly the port, improvements are to come!

**Comment by 0Navis0** [comment]
Yeah I understand, I won't bother you more, I just wanted to notice you it. I will talk of it to WaterPower dev. ;)
Anyway thanks so much for having updated this mod, it's so awesome. <3
