### ISSUE TITLE
For the life of me i cannot get power to MFFS.

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [nekosune/modularforcefieldsystem#31]
Using either Conduits from EnderIO (FE), FluxDucts (RF) and IC2 Cables (EU).

And there is only IC2 recipes.

I have tried everything, and even forcing it to accept power

1.12.2

**Comment by Chocohead** [comment]
You are trying to put the power into an MFFS Extractor right? The other blocks need the Force Energy it creates.
