### ISSUE TITLE
mod not working version 1.12.2-4.0.1.0_1.12_cc3a5aa

### ISSUE THREAD

**Issue by Nbgreen** [nekosune/modularforcefieldsystem#35]
when I try using the mod the game crashes on start up with the same error each time something to do with "LightGuideBook" here is a link to the crash report https://paste.dimdev.org/ijicuzuxog.mccrash

**Comment by GaeaKat** [comment]
Please also install the current dependencies - Guide-API and Ender IO , you may find the link at the bottom of this page under dependencies - https://minecraft.curseforge.com/projects/modular-forcefield-system/files/2581227
