### ISSUE TITLE
printing out state type messages into server console

### ISSUE THREAD

**Issue by YOYOK9** [nekosune/modularforcefieldsystem#5]
So noticed when I put MFFS into my server it was doing some rather interesting things in console. 
The modular forcefield project is printing out state type messages into server console, The number changes depending on what projector module is inserted into the projector.

Printing: "With state type: 0" 

Extra notes: 
- Server doesn't crash
- Doesn't seem to lag 
=================
Forge: 2185
MC: 1.10.2
MFFS: 1.10.2-3.0.0.0-1.10-655de1f

FML console:
https://gist.github.com/YOYOK9/4d5ee632c6bebb327aede2f19c3741ed

**Comment by GaeaKat** [comment]
Will fix this! sorry!

**Comment by YOYOK9** [comment]
ok sweet. Thanks for fast reply

**Comment by Alaberti** [comment]
Has this been fixed?
